export default function SettingsPage(){

    return (
        <>
            <div>This is SettingsPage</div>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-我到底了</p>
        </>
    );
}