export default function MessagePage(){

    return (
        <>
            <div>This is MessagePage</div>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-</p>
            <p>content-我到底了</p>
        </>
    );
}